# This is a basic workflow to help you get started with Actions

name: update mainfest on push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
      dst_token: ${{ secrets.GITEE_TOKEN }}
      gitee_user: ${{ secrets.GITEE_USER }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs merge
    # 注意：run 里面只有中间第二段和第三段的4行可以自定义，严格意义上只有第三段的那一行可以
    - name: Run merge
      run: |
        home=$(pwd)
        scripts_dir=$home'/scripts/'
        rules_dir=$home'/rules/'
        bash $scripts_dir/cp_scripts.sh $scripts_dir $home

        bash merge_rules.sh $rules_dir $home
        bash merge.sh $rules_dir $home
        mv $rules_dir/manifest.json $home/manifest.json

        bash merge_classes.sh ./classes/noSniffer/ $home

        cd $home
        bash $scripts_dir/clean_scripts.sh $home
        bash $scripts_dir/clean_scripts.sh $rules_dir

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "update mainfest" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        branch: ${{ github.ref }}
    - name: Mirror with force push (git push -f)
      uses: Yikun/hub-mirror-action@master
      if: env.dst_key && env.dst_token && env.gitee_user
      with:
        # 必选，需要同步的 Github 用户（源）
        src: 'github/${{ github.repository_owner }}'
        # 必选，需要同步到的 Gitee 用户（目的）
        dst: 'gitee/${{ secrets.GITEE_USER }}'
        # 必选，Gitee 公钥对应的私钥，https://gitee.com/profile/sshkeys
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        # 必选，Gitee 对应的用于创建仓库的 token，https://gitee.com/profile/personal_access_tokens
        dst_token: ${{ secrets.GITEE_TOKEN }}
        # 直接取当前项目的仓库名
        static_list: ${{ github.event.repository.name }}
        force_update: true
